title: Ujjwal Ranjan # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Lead AI/ML Engineer
  <br><br>
  <a href="mailto:ujjwalranjan88@gmail.com">ujjwalranjan88@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/ujjwal-r-95b649176/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/ujjwalranjan">Github</a>
theme: jekyll-theme-minimal
